services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dani
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  parcauto-api:
    container_name: parcauto-api
    image: dani606/parcauto-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/parcauto
    ports:
      - "8088:8081"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/parcauto
networks:
  db:
    driver: bridge

volumes:
  db:

